package chemistmod.reagents;

public enum MixResultEnum {
    DUD,

    MEGA_POTION,
    MEGA_ETHER,
    HALF_ELIXIR,
    RESURRECTION,
    GALVANIZING_AGENT,
    PHOENIX_FIRE,
    PANACEA,

    DRAGONS_FEAST,
    DRAGONS_BREATH,
    DRAGONS_SCALES,
    DRAGONS_CURSE,
    DRAGONS_RAGE,

    CARAPACE_COCKTAIL,
    STORMS_EYE,
    HARDENING_SOLUTION,
    CETACEAN_WRATH,

    CURSED_GAZE
}
