package chemistmod.reagents;

public enum MixResultEnum {
    DUD,

    MEGA_POTION,
    MEGA_ETHER,
    HALF_ELIXIR,
    RESURRECTION,
    PHOENIX_FIRE,
    PANACEA,

    DRAGONS_FEAST,
    DRAGONS_BITE,
    DRAGONS_BREATH,
    DRAGONS_CLAW,
    DRAGONS_GLARE,
    DRAGONS_SCALES,
    DRAGONS_CURSE,
    DRAGONS_RAGE,

    CARAPACE_COCKTAIL,
    OCEANS_FURY,
    STORMS_EYE,
    CALM_OF_THE_DEPTHS,
    TBD_1,
    HARDENING_SOLUTION,
    CETACEAN_WRATH,

    DEMONS_EMBRACE,
    DEVILS_TOUCH,
    FIENDS_CARESS,
    TBD_2
}
